version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/src'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
    commit-message:
      prefix: 'src'
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'dev'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
